const OPERATION_NAME = {
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    VERIFY_EMAIL: "VERIFY_EMAIL",
    UPGRADE: "UPGRADE",
}
const OPERATION_STATUS = {
    STARTED: "STARTED",
    OTP_SENT:"OTP_SENT",
    OTP_CORRECT:"OTP_CORRECT",
    CARD_SAVED: "CARD_SAVED",
    COMPLETED: "COMPLETED",
    UPGRADE_REQUESTED: "UPGRADE_REQUESTED",
    UPGRADE_REJECTED: "UPGRADE_REJECTED",
    UPGRADE_APPROVED: "UPGRADE_APPROVED",
}
const SUPPORT_TICKET_STATUS = {
    OPEN: "OPEN",
    IN_PROGRESS: "IN_PROGRESS",
    WAITING_FOR_USER: "WAITING_FOR_USER",
    RESOLVED: "RESOLVED",
    CLOSED: "CLOSED"
}
const ORDER_STATUS = {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    PROCESSING: "PROCESSING",
    SHIPPED: "SHIPPED",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
    REFUNDED: "REFUNDED",
    CANCELLING: "CANCELLING",
    BLOCKED: "BLOCKED",
}
const CATEGORY = {
    ELECTRONICS: "ELECTRONICS",
    CLOTHING: "CLOTHING",
    BOOKS: "BOOKS",
    HOME_GARDEN: "HOME_GARDEN",
    SPORTS: "SPORTS",
    BEAUTY: "BEAUTY",
    TOYS: "TOYS",
    AUTOMOTIVE: "AUTOMOTIVE",
    FOOD: "FOOD",
    HEALTH: "HEALTH"
}
const ERROR_MESSAGES = {
    VALIDATION_ERROR: {status: 422, message: "Validation Error"},
    USERNAME_PASSWORD_INCORRECT: {status: 400, message: 'Please check your credentials!'},
    EMAIL_PASSWORD_INCORRECT: {status: 400, message: 'Please check your credentials!'},
    UNAUTHORIZED: {status: 401, message: "UNAUTHORIZED"},
    ADMIN_RESTRICTED: {status: 401, message: "ADMIN_RESTRICTED"},
    USER_RESTRICTED: {status: 401, message: "USER_RESTRICTED"},
    FORBIDDEN: {status: 403, message: "FORBIDDEN"},
    USER_ALREADY_EXISTS: {status: 409, message: "USER_ALREADY_EXISTS"},
    OPERATION_IN_PROGRESS: {status: 409, message: "OPERATION_IN_PROGRESS"},
    OTP_EXPIRED: {status: 409, message: "OTP_EXPIRED"},
    EMAIL_NOT_SENT: {status: 409, message: "EMAIL_NOT_SENT"},
    WRONG_OTP: {status: 409, message: "WRONG_OTP"},
    CARD_DOES_NOT_EXIST: {status: 409, message: "CARD_DOES_NOT_EXIST"},
    PRODUCT_DOES_NOT_EXIST: {status: 409, message: "PRODUCT_DOES_NOT_EXIST"},
    CART_DOES_NOT_EXIST: {status: 409, message: "CART_DOES_NOT_EXIST"},
    PRODUCT_OUT_OF_STOCK: {status: 409, message: "PRODUCT_OUT_OF_STOCK"},
    CART_LIMIT_REACHED: {status: 409, message: "CART_LIMIT_REACHED"},
    CART_ITEMS_LIMIT_REACHED: {status: 409, message: "CART_ITEMS_LIMIT_REACHED"},
    PRODUCT_IS_NOT_IN_CART: {status: 409, message: "PRODUCT_IS_NOT_IN_CART"},
    ORDER_DOES_NOT_EXIST: {status: 409, message: "ORDER_DOES_NOT_EXIST"},
    ORDER_ALREADY_CANCELLED: {status: 409, message: "ORDER_ALREADY_CANCELLED"},
    ORDER_CANNOT_BE_CANCELLED: {status: 409, message: "ORDER_CANNOT_BE_CANCELLED"},
    CHAT_DOES_NOT_EXIST: {status: 409, message: "CHAT_DOES_NOT_EXIST"},
    TICKET_DOES_NOT_EXIST: {status: 409, message: "TICKET_DOES_NOT_EXIST"},
    TICKET_ALREADY_CLOSED: {status: 409, message: "TICKET_ALREADY_CLOSED"},
    CART_IS_EMPTY: {status: 409, message: "CART_IS_EMPTY"},
}
const LIMITS = {
    CART_LIMIT: 3,
    CART_ITEMS_LIMIT: 100,
}

const ERRORS = {}
Object.keys(ERROR_MESSAGES).forEach(key => {
    ERRORS[key] = key;
});

module.exports = {OPERATION_NAME, OPERATION_STATUS, SUPPORT_TICKET_STATUS, ORDER_STATUS, CATEGORY, ERROR_MESSAGES, ERRORS, LIMITS};